# Note: paths are relative to the *filesystem* directory in the Bedelllibrary folder.

local_storage_extension: "_DATA"

pdf_sources:
  - ../tests/pdf
  
store_pdf_sources_locally: True
store_pdf_sources_mongodb: False
mongodb_path_pdf_sources: None

tex_sources:
  - ../tests/tex_notes
  
store_tex_sources_locally: True
store_tex_sources_mongodb: False
mongodb_path_tex_sources: None

notebook_sources:
  - ../tests/notebook

store_notebook_sources_locally: True
store_notebook_sources_mongodb: False
mongodb_path_notebook_sources: None
